dist: bionic
sudo: false
language: ruby
rvm: 2.6.6
env:
  global:
  - DB_USER=postgres
  - DB_PASS=
addons:
  postgresql: 10
services:
- postgresql
- redis-server
cache:
  bundler: true
before_install:
- gem install bundler -v='2.0.2'
- bundle config set without 'production'
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
- bundle exec rails db:test:prepare
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- bundle exec rails spec
after_success:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: heroku
  app: tasafojobs
  skip_cleanup: true
  on:
    branch: master
  api_key:
    secure: BeNgp4MYRrh0HfoxSlso7lh873h797OCu4prS9XpmTLzgKjKML7spnU95zQSMMdz35eCdaChSnXO4Pc25JPjHt5Lu3VF2/duNa2L7UThY7VFnqPl6vgukw+6L3FGVMLPF6M9I48PY4a3wlnd9TKd3XNBehvoNwpWr2MdU1lj4Rw=
  run:
  - rails db:migrate
