== README

# Install Mailcatcher locally for development email management

`$ gem install mailcatcher`

Run Mailcatcher when you need to test emails

`$ mailcatcher`

Open http://127.0.0.1:1080 in your browser

# Prepare database

`$ rake db:create`
`$ rake db:migrate`
`$ rake db:test:prepare`

# Run tests

`$ rspec .`

# Run SEED on development and production

`$ rake db:seed`
`$ heroku run rake db:seed`

# Run server locally

`$ rails s`

# Sign up or sign in with users generated by seed:

david@email.com   / pass: 12345678
maria@email.com   / pass: 12345678
john@email.com    / pass: 12345678
mark@email.com    / pass: 12345678
terry@email.com   / pass: 12345678
amanda@email.com  / pass: 12345678
